driver:
  name: digitalocean
  flavor: 2GB
  region : Singapore 1
  private_networking: false
  ssh_key: <%= ENV['DO_SSH_KEY'] %>
  require_chef_omnibus: true

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-12.10
    run_list: apt::default
    driver:
      image_id: 3101891
      username: root
  - name: centos-6
    driver:
      image_id: 3102789
      username: root

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user: root
        build_dir: /usr/local/serverspec
        install_dir: /opt/serverspec
