driver:
  name: vagrant
  provider: digital_ocean
  box: digital_ocean
  box_url: https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box
  vagrantfile_erb: <%= File.join(File.dirname(__FILE__), "templates/Vagrantfile.erb") %>
  digitalocean:
    provider:
      token: <%= ENV['DIGITALOCEAN_TOKEN'] %>
      ssh_key_name: <%= ENV['DO_SSH_KEY_NAME'] %>
      size: 2GB
      region: sgp1
    override:
      ssh.private_key_path: <%= ENV['DO_SSH_KEY'] %>
  synced_folders:
    - ['./', '/home/vagrant/serverspec']

provisioner:
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
    driver:
      digitalocean:
        provider:
          image: ubuntu-14-04-x64
  - name: centos-6.5
    driver:
      digitalocean:
        provider:
          image: centos-6-5-x64

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/serverspec
        install_dir: /opt/serverspec
        ruby_version: 2.1.5
