---
version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/omnibus-serverspec
    steps:
      - checkout
      - restore_cache:
          key: omnibus-{{ .Branch }}
          paths:
            - /home/circleci/omnibus-serverspec/.omnibus_cache
            - /home/walter
      - run:
          name: install walter
          command: ./ci/install-walter-1.3.0.sh
      - run:
          name: install jfrog-cli
          command: |
            go get github.com/jfrogdev/jfrog-cli-go/jfrog-cli/jfrog
            mkdir -p ~/.jfrog && echo '{"bintray":{}}' > ~/.jfrog/jfrog-cli.conf
      - run:
          name: build images to test
          command: |
            bash -c 'mkdir -p ~/.omnibus_cache/{ubuntu14,centos6}'
            docker pull opsrock/omnibus_base_ubuntu14
            docker pull opsrock/omnibus_base_centos6
            docker build -t builder-ubuntu1404 -f docker/Dockerfile.ubuntu1404 .
            docker build -t builder-centos6 -f docker/Dockerfile.centos6 .
            ~/bin/walter -c ci/walter_build.yml
      - save_cache:
          key: omnibus-{{ .Branch }}
          paths:
            - /home/circleci/omnibus-serverspec/.omnibus_cache
            - /home/walter
      - store_artifacts:
           path: /home/circleci/omnibus-serverspec/pkg
           destination: pkg
