---
version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/omnibus-serverspec
    steps:
      - checkout
      - restore_cache:
          key: omnibus-{{ .Branch }}
          paths:
            - /home/circleci/omnibus-serverspec/.omnibus_cache
            - /home/circleci/walter
            - /home/circleci/.go_workspace
      - run:
          name: install walter
          command: ./ci/install-walter-1.3.0.sh
      - run:
          name: build images to test
          command: |
            bash -c 'mkdir -p ~/.omnibus_cache/{ubuntu14,centos6}'
            docker pull opsrock/omnibus_base_ubuntu14
            docker pull opsrock/omnibus_base_centos6
            docker build -t builder-ubuntu1404 -f docker/Dockerfile.ubuntu1404 .
            docker build -t builder-centos6 -f docker/Dockerfile.centos6 .
            ~/bin/walter -c ci/walter_build.yml
      - run:
          name: export versions.json
          command: |
            gem update --system
            gem install bundler --no-ri --no-rdoc
            bundle install --without development test ship
            bundle exec rake > pkg/versions.json
      - store_artifacts:
           path: /home/circleci/omnibus-serverspec/pkg
           destination: pkg
      - run:
          name: prepare persist_to_workspace
          command: |
            mkdir -p /tmp/workspace
            cp -a pkg /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pkg
      - save_cache:
          key: omnibus-{{ .Branch }}
          paths:
            - /home/circleci/omnibus-serverspec/.omnibus_cache
            - /home/circleci/walter
            - /home/circleci/.go_workspace
      - store_artifacts:
           path: /home/circleci/omnibus-serverspec/pkg
           destination: pkg
  test:
    machine: true
    working_directory: /home/circleci/omnibus-serverspec
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: install built pkgs
          command: |
            docker run -v /tmp/workspace/pkg:/opt/pkg ubuntu:trusty find /opt/pkg/ -name "*deb" -exec dpkg -i {} \;
            docker run -v /tmp/workspace/pkg:/opt/pkg centos:6 find /opt/pkg/ -name "*rpm" -exec rpm -ivh {} \;
            docker run -v /tmp/workspace/pkg:/opt/pkg centos:7 find /opt/pkg/ -name "*rpm" -exec rpm -ivh {} \;
  deployment:
    machine: true
    working_directory: /home/circleci/omnibus-serverspec
    steps:
      - checkout
      - restore_cache:
          key: omnibus-deployment-{{ .Branch }}
          paths:
            - /home/circleci/walter
            - /home/circleci/.go_workspace
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: install walter
          command: ./ci/install-walter-1.3.0.sh
      - run:
          name: install jfrog-cli
          command: |
            go get github.com/jfrogdev/jfrog-cli-go/jfrog-cli/jfrog
            mkdir -p ~/.jfrog && echo '{"bintray":{}}' > ~/.jfrog/jfrog-cli.conf
      - run:
          name: install package_cloud
          command: |
            gem update --system
            gem install bundler --no-ri --no-rdoc
            bundle install --without development test
      - run:
          name: shipit
          command: |
            jfrog --version
            find /tmp/workspace
            cp -av /tmp/workspace/pkg/* pkg/
      - save_cache:
          key: omnibus-deployment-{{ .Branch }}
          paths:
            - /home/circleci/walter
            - /home/circleci/.go_workspace

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - test
