---
version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/omnibus-serverspec
    steps:
      - checkout
      - restore_cache:
          key: omnibus-{{ .Branch }}
          paths:
            - /home/circleci/omnibus-serverspec/.omnibus_cache
            - /home/circleci/walter
            - /home/circleci/.go_workspace
      - run:
          name: install walter
          command: ./ci/install-walter-1.3.0.sh
      - run:
          name: build images to test
          command: |
            bash -c 'mkdir -p ~/.omnibus_cache/{ubuntu14,centos6}'
            docker pull opsrock/omnibus_base_ubuntu14
            docker pull opsrock/omnibus_base_centos6
            docker build -t builder-ubuntu1404 -f docker/Dockerfile.ubuntu1404 .
            docker build -t builder-centos6 -f docker/Dockerfile.centos6 .
            ~/bin/walter -c ci/walter_build.yml
      - run:
          name: ruby-version
          command: |
            gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
            rvm get stable
            rvm use 2.5 --default
            echo ruby-2.5 > .ruby-version
      - run:
          name: export versions.json
          command: |
            gem update --system
            gem install bundler --no-document
            bundle install --without development test ship omnibus
            bundle exec rake > pkg/versions.json
      - store_artifacts:
           path: /home/circleci/omnibus-serverspec/pkg
           destination: pkg
      - run:
          name: prepare persist_to_workspace
          command: |
            mkdir -p /tmp/workspace
            cp -a pkg /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - pkg
      - save_cache:
          key: omnibus-{{ .Branch }}
          paths:
            - /home/circleci/omnibus-serverspec/.omnibus_cache
            - /home/circleci/walter
            - /home/circleci/.go_workspace
      - store_artifacts:
           path: /home/circleci/omnibus-serverspec/pkg
           destination: pkg
  test:
    machine: true
    working_directory: /home/circleci/omnibus-serverspec
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: install built pkgs
          command: |
            for x in xenial bionic ; do
              docker run -v /tmp/workspace/pkg:/opt/pkg -v `pwd`/test/test_deb.sh:/tmp/test.sh ubuntu:${x} bash /tmp/test.sh
            done
            for x in {6..8} ; do
              docker run -v /tmp/workspace/pkg:/opt/pkg -v `pwd`/test/test_rpm.sh:/tmp/test.sh centos:${x} bash /tmp/test.sh
            done
  deployment:
    machine: true
    working_directory: /home/circleci/omnibus-serverspec
    steps:
      - checkout
      - restore_cache:
          key: omnibus-deployment-{{ .Branch }}
          paths:
            - /home/circleci/walter
            - /home/circleci/.go_workspace
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: install walter
          command: ./ci/install-walter-1.3.0.sh
      - run:
          name: install jfrog-cli
          command: curl -fL https://getcli.jfrog.io | sh -x
      - run:
          name: setup jfrog-cli
          command: |
            mkdir -p ~/bin
            mv ./jfrog ~/bin/
            mkdir -p ~/.jfrog && echo '{"bintray":{}}' > ~/.jfrog/jfrog-cli.conf
      - run:
          name: ruby-version
          command: |
            gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
            rvm get stable
            rvm use 2.5 --default
            echo ruby-2.5 > .ruby-version
      - run:
          name: install package_cloud
          command: |
            gem update --system
            gem install bundler --no-document
            bundle install --without development test omnibus
      - run:
          name: shipit
          command: |
            cp -av /tmp/workspace/pkg/* pkg/
            ~/bin/walter -c ci/walter_release.yml
      - save_cache:
          key: omnibus-deployment-{{ .Branch }}
          paths:
            - /home/circleci/walter
            - /home/circleci/.go_workspace

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
                - /build_.*/
