pipeline:
  - name: Build pkgs
    parallel:
      - name: ubuntu14
        type: command
        command: docker run -e OMNIBUS_PROJECT=serverspec -e CIRCLE_BUILD_NUM -v pkg:/home/omnibus/omnibus-project/pkg builder-ubuntu1404
      - name: centos6
        type: command
        command: docker run -e OMNIBUS_PROJECT=serverspec -e CIRCLE_BUILD_NUM -v pkg:/home/omnibus/omnibus-project/pkg builder-centos6
