pipeline:
  - name: Build pkgs
    parallel:
      - name: ubuntu14
        type: command
        command: docker run -e OMNIBUS_PROJECT=serverspec -e CIRCLE_BUILD_NUM -v $HOME/$CIRCLE_PROJECT_REPONAME/pkg:/home/omnibus/omnibus-project/pkg -v $HOME/.omnibus_cache/ubuntu14:/home/omnibus/omnibus-project/local builder-ubuntu1404
      - name: centos6
        type: command
        command: docker run -e OMNIBUS_PROJECT=serverspec -e CIRCLE_BUILD_NUM -v $HOME/$CIRCLE_PROJECT_REPONAME/pkg:/home/omnibus/omnibus-project/pkg -v $HOME/.omnibus_cache/centos6:/home/omnibus/omnibus-project/local builder-centos6
