pipeline:
  - name: Build pkgs
    parallel:
      - name: ubuntu16
        type: command
        command: docker run -e OMNIBUS_PROJECT=serverspec -e BUILD_ITERATION=$GITHUB_RUN_NUMBER -e BUILD_CACHE_PATH=/home/omnibus/omnibus-project/local/omnibus/cache/install_path/opt/serverspec -v $GITHUB_WORKSPACE/pkg:/home/omnibus/omnibus-project/pkg builder-ubuntu1604
      - name: centos7
        type: command
        command: docker run -e OMNIBUS_PROJECT=serverspec -e BUILD_ITERATION=$GITHUB_RUN_NUMBER  -e BUILD_CACHE_PATH=/home/omnibus/omnibus-project/local/omnibus/cache/install_path/opt/serverspec -v $GITHUB_WORKSPACE/pkg builder-centos7
