# https://docs.github.com/ja/actions/reference/context-and-expression-syntax-for-github-actions
name: Release

on:
 - push
 - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.5
      - name: install walter
        run: ./ci/install-walter-1.3.0.sh
      - name: build images to test
        run: |
          bash -c 'mkdir -p ~/.omnibus_cache/{ubuntu16,centos7}'
          docker pull opsrock/omnibus_base_ubuntu16
          docker pull opsrock/omnibus_base_centos7
          docker build -t builder-ubuntu1604 -f docker/Dockerfile.ubuntu1604 .
          docker build -t builder-centos7 -f docker/Dockerfile.centos7 .
          ~/bin/walter -c ci/walter_build.yml
      - name: export versions.json
        run: |
          gem update --system
          gem install bundler --no-document
          bundle config set without "development test ship omnibus"
          bundle install
          bundle exec rake > pkg/versions.json
